### ISSUE TITLE
mlaps roxygen @details typo

### ISSUE THREAD

**Issue by vaakesan-SMH** [GEMINI-Medicine/Rgemini#100]
Currently the `@details` section mentions that the score takes 14 lab test values, when in fact it is now 13. Make the change from this:

> Modified Laboratory based Acute Physiology Score (mLAPS) uses 14 lab test values. In this modified version, High senstive Troponin tests are ignored and treated as normal.

To this:

> Modified Laboratory based Acute Physiology Score (mLAPS) uses 13 lab test values. In this modified version, High senstive Troponin tests are ignored and treated as normal.

**Comment by kayleymarchena** [comment]
@kayleymarchena

**Comment by loffleraSMH** [comment]
Note: This should actually say "**12** lab test values from 11 unique lab tests", which has been fixed now. Thanks @marchenaromk!
