### ISSUE TITLE
Homelessness indicator development

### ISSUE THREAD

**Issue by shijiaSMH** [GEMINI-Medicine/Rgemini#114]
Will add a homelessness function when specific implementation is agreed by group, based on conceptual and empirical evidence

**Comment by shijiaSMH** [comment]
**Function development - skeleton codes**
```
Homelessness <- function(data, ipdiagnosis, erdiagnosis){
data[, homeless := F]
 data[genc_id %in% ipdiagnosis[diagnosis_code %in% c('Z590', 'Z591')]$genc_id |
     genc_id %in% erdiagnosis[er_diagnosis_code %in% c('Z590', 'Z591')]$genc_id, homeless := T]
}
```
 
**Documentation**
- Purpose: This function returns an encounter-based homelessness flag using ICD-10-CA diagnosis codes.
- Input arguments: data = a genc_id list, ipdiagnosis, erdiagnosis
- The accuracy of this function relies on maintained of Z59.0 Homelessness and Z59.1 Inadequate Housing codes in hospitals
- Pre-2018 limitations: It's expected to see significantly lower rate of homelessness before 2018 than rates after 2018 due to CIHI mandate.
- Use recommendation: We recommend to use this flag in descriptive analysis
- Report recommendation: This flag is a validated, adapted flag of ICES validated homelessness indicator
- Reference 1: CIHI mandate to code Z59.0 Homelessness in 2018: https://www.cihi.ca/en/better-quality-hospital-data-for-identifying-patients-experiencing-homelessness
- Reference 2: ICES validated homelessness indicator: https://bmjopen.bmj.com/content/9/10/e030221

**Comment by loffleraSMH** [comment]
Please use the exact same argument/code structure as in `covid_flag()` function (see here: https://github.com/GEMINI-Medicine/Rgemini/blob/master/R/covid_flag.R).
