### ISSUE TITLE
Add plotting functions for exploratory analyses

### ISSUE THREAD

**Issue by loffleraSMH** [GEMINI-Medicine/Rgemini#14]
## New Feature Request

Adding a first set of functions that facilitate common ways of exploring the data and visualizing some basic stats:

1. Summary plot with basic descriptive histograms/barplots for multiple variables
2. Function plotting a variable over time (and grouped by hospital, or other grouping variables).

Suggested developers:

* @sophialaird 
* @loffleraSMH

**Comment by shijiaSMH** [comment]
@loffleraSMH, adding a couple of ideas for more flexibility here, let's add those if they are quick fixes. If not, let's leave them for next time.

1. Show both scattered dots and line; use simple linear regression to fit a smoother line to see trends better
![image](https://github.com/GEMINI-Medicine/Rgemini/assets/105071952/4b4a935f-d93f-41c3-b391-471ba9190825)

2. Flexibility for line types and dot types
![image](https://github.com/GEMINI-Medicine/Rgemini/assets/105071952/4542c4bc-6759-40bf-bf14-cae66d92d5c5)
![image](https://github.com/GEMINI-Medicine/Rgemini/assets/105071952/99132594-84d6-435e-9e42-7eea483b1892)

3. Flexibility to add text/label
![image](https://github.com/GEMINI-Medicine/Rgemini/assets/105071952/fbeeb497-21b8-476f-a4cf-c4d81a729d1b)

**Comment by loffleraSMH** [comment]
@shijiaSMH: Hm, let me think about whether we can add 1 (but I might open a new issue for this). Not sure about 2 (we could add a simplified version of this but this is getting into very user-specific needs that might make the function unnecessarily complex for a basic exploratory/descriptive plot). 3. can simply be achieved by users adding any additional layers to the plot with `+` so no need to change the function for this.

**Comment by shijiaSMH** [comment]
sorry just added 4. time cut, can you see?

Cool just don't want any inflexibility for users to not use those functions!

**Comment by loffleraSMH** [comment]
4. can also be added by users with a single line of code, once the basic plot was returned by the function, correct?
Yep, let's make sure the basic versions of these functions work properly first (there is already lots of potential for bugs) and then we can add other enhancements (based on demand) later on?

**Comment by loffleraSMH** [comment]
Yep, I generally agree. Just keep in mind a) the purpose of the function (I don't think people should rely on this to produce their main results figure for a manuscript) and b) the function also needs to be user-friendly. The main strength of this function is automating all the aggregation steps. If users have specific plotting needs, they can use `return_data` and then plot the results however they like. 
Anyway, for now, I've added a `smooth_method` input argument that allows users to add a smoothed trend line. I also added an example for how to add annotations/vertical lines to figures in the vignette. I also split the functions for data exploration vs. plotting themes into 2 separate vignettes. Hopefully, that clarifies the scope/main goal of each function a little bit clearer.

**Comment by shijiaSMH** [comment]
Had another quick thought: automating all the aggregation steps is the main strength, then maybe if we find bugs, we can leave out some arguments? 

It looks like a feature is done adding a line of '+..', the same as adding all other additional features. I guess all the arguments are there since we believe they are commonly used for exploration purpose?

**Comment by loffleraSMH** [comment]
Correct, the current input arguments are optimized to improve usability without users having to specify too many input arguments. None of the current arguments' full functionality could be implemented with a single `+` outside of the function. If we find a bug with the current arguments, we should just fix that bug.
