### ISSUE TITLE
Add function(s) checking missing values

### ISSUE THREAD

**Issue by loffleraSMH** [GEMINI-Medicine/Rgemini#28]
## New Feature Request

There are currently a few different functions in `GEMINIpkg` that check for missing values:
- `count_missing()`
- `mi2()` [identical to `count_missing`?]
- `return_missing_index()`

Similarly to the suggestions made in issue #29, these functions should ideally be combined into a single, improved function within `Rgemini`. Ideally, the function checks for the number/% of missing values, and optionally (based on user input), also returns the index of any missing entries. Maybe we could also improve this function to work for both vector and table inputs (for tables, it would return n/% missing per column)? 

Please coordinate with developer working on #29 to align function arguments/outputs since the 2 functions are conceptually somewhat similar. 

Please name function appropriately with descriptive name(s) and follow [Code Review Checklist](https://docs.google.com/document/d/16kiIgwWjXYhBM5AFToXD7X9OjqNYs0xQZh9VDfSwYQU/edit?usp=sharing) for additional guidelines.

Once the improved function has been developed & reviewed in `Rgemini`, all 3 functions listed above should be deprecated from `GEMINIpkg` and should be moved to the `Deprecated.R` script.

Any suggested developers?

* 

Any suggested reviewers?

*

**Comment by guoyi-smh** [comment]
Current version of `mi2()` and `count_missing` do not work when the input is in POSIXt date time format.
