### ISSUE TITLE
Add function checking duplicated values

### ISSUE THREAD

**Issue by loffleraSMH** [GEMINI-Medicine/Rgemini#29]
## New Feature Request

There are a couple of functions in `GEMINIpkg` checking for duplicated values:
- `check_number_duplicated()` 
- `dup_any()` (in `utils.R`)

Similarly to the suggestions made in issue #28, these two functions should ideally be combined into a single, improved function within `Rgemini`.  Ideally, the function checks for the number/% of duplicated values, and optionally (based on user input), also returns the index of any duplicated entries. 

Please coordinate with developer working on #28 to align function arguments/outputs since the 2 functions are conceptually somewhat similar. 

Note that `check_number_duplicated` does not work for `data.table`/`data.frame` inputs but only for vectors. Ideally, the improved function should work for either of those input types. 

Please name function appropriately with descriptive name(s) and follow [Code Review Checklist](https://docs.google.com/document/d/16kiIgwWjXYhBM5AFToXD7X9OjqNYs0xQZh9VDfSwYQU/edit?usp=sharing) for additional guidelines.

Once the improved function has been developed & reviewed in `Rgemini`, the 2 functions listed above should be deprecated from `GEMINIpkg` and should be moved to the `Deprecated.R` script.

Any suggested developers?

* 

Any suggested reviewers?

*

**Comment by guoyi-smh** [comment]
This will not be implemented as there is currently no need.

**Comment by guoyi-smh** [comment]
I think it is okay to deprecate them. I will do it in the merge request to deprecate the missingness functions.

**Comment by loffleraSMH** [comment]
Perfect, sounds good!
