### ISSUE TITLE
Table1: Different handling of digits for continuous vs. categorical variables

### ISSUE THREAD

**Issue by loffleraSMH** [GEMINI-Medicine/Rgemini#35]
Please identify the affected function: 

`cell_suppression.R` for `table1`

The renders for categorical vs. continuous variables currently handle the `digits` argument differently. For continuous variables, there seems to be a bug where the digits before the decimal point are included in the digit count. For categorical variables, the behaviour is as expected (digits after decimal point). Here is an example:

```
set.seed(999)
gender <- c(sample(c("M", "F"), size = 95, replace = TRUE), rep(NA, times = 5))
age <- rnorm(100, mean = 70, sd = 5)

data <- data.frame(gender = gender, age = age)

tab1 <- table1(~gender + age,
               data = data,
               render.categorical = render_strict_cell_suppression.categorical,
               digits = 5)

tab1
```
![Screenshot 2023-11-24 153935](https://github.com/GEMINI-Medicine/Rgemini/assets/104941195/a112fe9c-f2ac-4b32-bb15-d27e33778ade)

*For the developer:* Once the bug is resolved, please add the reproducible example above as a test in the `tests/testthat` directory.

Any suggested developers?

* 

Any suggested reviewers?

*

**Comment by vaakesan-SMH** [comment]
Needs to change `sprintf` format in `render_cell_suppression.categorical()` and `render_strict_cell_suppression.categorical()` from:

```
paste0("%d (%0.", args$digits, "f%%)")
```

to

```
sprintf(paste0("%d (%.", args$digits, "g%%)"), frequency, pct)
```

To use "significant digits" rather than "digits after the decimal".

**Comment by loffleraSMH** [comment]
@vaakesan-SMH Oh I see, so you would change how categorical variables are handled? I thought it's more intuitive to count digits after the decimal point (i.e., leave categorical as is, but change the behaviour for continuous variables).

**Comment by vaakesan-SMH** [comment]
Agree it's more intuitive to count digits after the decimal point. This is only an issue if the user is "mixing and matching" between `table1` native render functions and `Rgemini` render functions:

```
set.seed(3)

exposure <- sample(
  c("pre-pandemic", "pandemic", "post-pandemic"), 
  size = 100, replace = TRUE
)

age <- rnorm(100, mean = 70, sd = 5)

condition <- sample(
  c("DVT", "CVD", "DM", "Pneumonia", "Dementia"), 
  size = 100, replace = TRUE, prob = c(0.01, 0.20, 0.4, 0.35, 0.05)
)

data <- data.frame(gender = gender, exposure = exposure, age = age, condition = condition)
```

```
library(Rgemini)
library(table1)

table1(
  ~ age + condition | exposure, data = data, 
  render.continuous = c(.="Mean (SD)", .="Median [Q1, Q3]"), 
  render.categorical = render_strict_cell_suppression.categorical, 
  digits = 5
  )
```

![image](https://github.com/GEMINI-Medicine/Rgemini/assets/104445289/04afaf7f-3a83-416f-a57c-c8b06f12d191)

They could change the native behavoiur like so:

```
table1(
  ~ age + condition | exposure, data = data, 
  render.continuous = c(.="Mean (SD)", .="Median [Q1, Q3]"), 
  render.categorical = render_strict_cell_suppression.categorical, 
  digits = 5,
  rounding.fn = round_pad
  )
```

![image](https://github.com/GEMINI-Medicine/Rgemini/assets/104445289/1eceba62-a132-4925-a1a4-be442e7d4728)

If using `Rgemini` continuous render functions:

```
table1(
  ~ age + condition | exposure, data = data, 
  render.continuous = render_cell_suppression.continuous, 
  render.categorical = render_strict_cell_suppression.categorical, 
  digits = 5
)
```

![image](https://github.com/GEMINI-Medicine/Rgemini/assets/104445289/49c5953c-470c-489a-8b02-bf688f2b29f9)

We get the desired result.

So either we change `Rgemini` behaviour to match `table1` default behaviour, or we document how to work around `table1` default behaviour if "mixing and matching" render functions.

**Comment by vaakesan-SMH** [comment]
Note that if we want to match `table1` default behaviour of rounding to total digits, we'd also have to change this:

```
stats.apply.rounding(stats.default(x, ...), rounding.fn = round_pad, ...)
```

to this:

```
stats.apply.rounding(stats.default(x, ...), rounding.fn = signif_pad, ...)
```

In `render_mean.continuous()` and `render_median.continuous()`.

**Comment by loffleraSMH** [comment]
I see, thanks for testing the different options - that's very helpful! Let's maybe discuss with the sprint team? Personally, I'd prefer to count digits after decimal point and document the workaround when mixing and matching. But I can see how that might be confusing so maybe worth discussing with more people.

**Comment by vaakesan-SMH** [comment]
Agreed. Lets discuss and then update the definition of done for this issue.
